// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvrI6f-eJVPx9sOICZQ1V0BFYnXTp0cwI',
    appId: '1:996782372505:web:4c06875bde4c33b3302a08',
    messagingSenderId: '996782372505',
    projectId: 'valery-38810',
    authDomain: 'valery-38810.firebaseapp.com',
    storageBucket: 'valery-38810.appspot.com',
    measurementId: 'G-DT1FPDYHNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoBx9R1zY0E00JPgHaQb9uTFzaKMr-BCU',
    appId: '1:996782372505:android:3ce616c5cc2e6bfc302a08',
    messagingSenderId: '996782372505',
    projectId: 'valery-38810',
    storageBucket: 'valery-38810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZQ962oAuG_RWCi0C_ZUqJ5VXNNQhEIjI',
    appId: '1:996782372505:ios:ef7d984dd0b27c17302a08',
    messagingSenderId: '996782372505',
    projectId: 'valery-38810',
    storageBucket: 'valery-38810.appspot.com',
    iosBundleId: 'com.johonbar.valery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZQ962oAuG_RWCi0C_ZUqJ5VXNNQhEIjI',
    appId: '1:996782372505:ios:2e41d7f7a068827b302a08',
    messagingSenderId: '996782372505',
    projectId: 'valery-38810',
    storageBucket: 'valery-38810.appspot.com',
    iosBundleId: 'com.johonbar.valery.RunnerTests',
  );
}
